Storyboard/Wireframe
GroupAlert/LifeLine pull request #2
Opened 2020-03-31 21:48 UTC by BallisticBall

Edits to storyboard to align to wireframes.

2020-04-02 23:18 UTC, markFalcone commented
@pv-gitjob @BallisticBall I don't like the contact page can we change the look of that by adding in a email field and a message spot so you can send a message and lifeline will email you back on the issue

2020-04-03 01:06 UTC, pv-gitjob commented
@markFalcone This branch is just James adjusting the storyboard and functions I already had to match his wireframe. If we added an email field we have to set up an email server or server sms, this is the best way to avoid all that. You can put 1800-something or even remove the forgot password thing altogether.

2020-04-03 01:07 UTC, pv-gitjob requested changes
Sigbart error when going to account settings.

2020-04-06 00:50 UTC, pv-gitjob approved these changes

2020-04-06 00:51 UTC, merged